In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import tensorflow_probability as tfp

In [4]:
x = tf.constant([[1,2,3],
                [4,5,6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [13]:
tf.math.reduce_mean(tf.cast(x, dtype=tf.float32), axis=1) #c

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

In [15]:
tf.random.set_seed(42)
y = tf.random.uniform(shape=[50])
y

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [16]:
tf.argmax(y) #index of max value

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [17]:
y[tf.argmax(y)] #max  value

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [20]:
y[tf.argmin(y)] #min  value from argmax

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [22]:
F = tf.random.uniform(shape=[50])

In [27]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [28]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [31]:
G_squeezed = tf.squeeze(G) # removes dimensions of size 1
G_squeezed.shape

TensorShape([50])

In [33]:
sl = [0,1,2,3]
tf.one_hot(sl, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [34]:
tf.range(1,10)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [36]:
tf.math.log(tf.cast(sl, dtype=tf.float32))

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([     -inf, 0.       , 0.6931472, 1.0986122], dtype=float32)>

In [40]:
tf.config.list_physical_devices("GPU")


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [41]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [4]:
x = tf.constant([1,2,3])

In [5]:
x.shape, x.ndim, tf.size(x)

(TensorShape([3]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=3>)

In [7]:
a = tf.random.uniform(shape=[5,300])
b = tf.random.uniform(shape=[5,300])

In [8]:
a*b

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[9.7214855e-02, 6.8283987e-01, 4.6915045e-01, ..., 3.1868109e-01,
        1.9935837e-01, 1.6831735e-01],
       [3.7006932e-01, 2.5982830e-01, 9.6369110e-02, ..., 2.5439388e-01,
        3.7332502e-01, 6.3099766e-01],
       [4.2325012e-02, 2.9624987e-01, 1.0963831e-02, ..., 3.2928433e-02,
        7.2478831e-02, 5.0696659e-01],
       [9.8737173e-02, 2.4248123e-02, 3.5224906e-01, ..., 4.6178430e-02,
        9.3674904e-01, 1.7130760e-02],
       [2.2463078e-05, 3.9769150e-03, 8.3200312e-01, ..., 5.0297564e-01,
        8.7400335e-01, 5.5517226e-01]], dtype=float32)>

In [10]:
tf.tensordot(a,tf.transpose(b), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 98.34755 ,  80.01209 ,  76.37611 ,  70.609406,  74.27988 ],
       [ 80.01209 , 107.65361 ,  74.474396,  72.36779 ,  79.742485],
       [ 76.37611 ,  74.474396,  99.239365,  71.1331  ,  72.19905 ],
       [ 70.609406,  72.36779 ,  71.1331  ,  89.66723 ,  69.21433 ],
       [ 74.27988 ,  79.742485,  72.19905 ,  69.21433 ,  99.42442 ]],
      dtype=float32)>

In [12]:
c = tf.random.uniform(shape=[224, 224], minval=0 ,maxval=1 )
c

<tf.Tensor: shape=(224, 224), dtype=float32, numpy=
array([[0.31179297, 0.8263413 , 0.6849456 , ..., 0.99757504, 0.52172756,
        0.20307171],
       [0.7182547 , 0.84263575, 0.9542595 , ..., 0.8703892 , 0.19604945,
        0.3441298 ],
       [0.16838431, 0.7888874 , 0.2256285 , ..., 0.4360633 , 0.7536833 ,
        0.01353109],
       ...,
       [0.9320761 , 0.7848129 , 0.16143286, ..., 0.19836617, 0.833007  ,
        0.34837723],
       [0.19666207, 0.02923715, 0.1339314 , ..., 0.561605  , 0.7435316 ,
        0.00272155],
       [0.8751484 , 0.5341966 , 0.43753648, ..., 0.7100389 , 0.3273698 ,
        0.09985757]], dtype=float32)>

In [15]:
tf.reduce_max(c)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9999734>

In [18]:
z = tf.squeeze(tf.random.uniform(shape=(1,224,3))).shape

In [23]:
tf.one_hot(z, depth=3)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [24]:
ten_tensor = tf.constant([0 ,1 ,2 ,3, 4, 9, 10, 0.1 , -000.1 , 6])

In [25]:
tf.math.argmax(ten_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [27]:
ten_tensor[tf.math.argmax(ten_tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [30]:
tf.one_hot(tf.cast(ten_tensor, dtype=tf.int32), depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)>

In [32]:
tf.constant([1,1,2,2])

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 1, 2, 2], dtype=int32)>