In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import tensorflow_probability as tfp

In [4]:
x = tf.constant([[1,2,3],
                [4,5,6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [13]:
tf.math.reduce_mean(tf.cast(x, dtype=tf.float32), axis=1) #c

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

In [15]:
tf.random.set_seed(42)
y = tf.random.uniform(shape=[50])
y

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [16]:
tf.argmax(y) #index of max value

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [17]:
y[tf.argmax(y)] #max  value

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [19]:
y[tf.argmin(y)] #min  value

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>